<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Storage;

class StatisticsController extends Controller
{
    public function index()
    {
        $type = request('type'); // get ?type=cswd, budget, treasury, accounting

        $analyticsViews = [
            'cswd'      => ['permission' => 'CSWD-ANALYTICS'],
            'budget'    => ['permission' => 'BUDGET-ANALYTICS'],
            'treasury'  => ['permission' => 'TREASURY-ANALYTICS'],
            'accounting' => ['permission' => 'ACCOUNTING-ANALYTICS'],
        ];

        if (!isset($analyticsViews[$type])) {
            abort(404, 'Invalid analytics type.');
        }

        $permission = $analyticsViews[$type]['permission'];

        if (!Gate::allows($permission)) {
            abort(403, 'You do not have permission to view this statistics.');
        }
        $this->runPythonAgeStats();
        return $this->getPythonJsonOutput();
    }

    protected function runPythonAgeStats()
    {
        $pythonPath = base_path('venv/Scripts/python.exe');  // Adjust path to your python executable
        $scriptPath = base_path('python/age_statistics.py'); // Your Python script path

        exec("\"$pythonPath\" \"$scriptPath\"", $output, $return_var);

        if ($return_var !== 0) {
            \Log::error("Python age statistics script failed", ['output' => $output]);
        }
    }

    // Return the JSON generated by the Python script
    protected function getPythonJsonOutput()
    {
        $jsonPath = storage_path('app/public/age_stats_output.json');

        if (!file_exists($jsonPath)) {
            return response()->json(['error' => 'No statistics data found'], 404);
        }

        $json = file_get_contents($jsonPath);
        $data = json_decode($json, true);

        return response()->json($data);
    }
}
