<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Storage;

class StatisticsController extends Controller
{
    public function index()
    {
        $type = request('type'); // get ?type=cswd, budget, treasury, accounting

        $analyticsViews = [
            'cswd'      => ['permission' => 'CSWD-ANALYTICS'],
            'budget'    => ['permission' => 'BUDGET-ANALYTICS'],
            'treasury'  => ['permission' => 'TREASURY-ANALYTICS'],
            'accounting' => ['permission' => 'ACCOUNTING-ANALYTICS'],
        ];

        if (!isset($analyticsViews[$type])) {
            abort(404, 'Invalid analytics type.');
        }

        $permission = $analyticsViews[$type]['permission'];

        if (!Gate::allows($permission)) {
            abort(403, 'You do not have permission to view this statistics.');
        }

        // Export CSV for Python script input
        $this->exportCsvFiles();

        // Run Python script to process CSV and generate JSON output
        $this->runPythonAgeStats();


        // Return JSON output from Python script
        return $this->getPythonJsonOutput();
    }

    // Export patient ages by case_category and case_type into CSV for Python
    protected function exportCsvFiles()
    {
        // Export patient ages CSV
        $ageData = DB::table('patient_records as pr')
            ->join('patient_status_logs as psl', 'psl.patient_id', '=', 'pr.id')
            ->select('pr.case_category', 'pr.case_type', 'pr.age')
            ->whereNull('pr.deleted_at')
            ->whereNull('psl.deleted_at')
            ->where('psl.status', 'Disbursed')
            ->get();

        $ageCsv = "case_category,case_type,age\n";
        foreach ($ageData as $row) {
            $ageCsv .= "\"{$row->case_category}\",\"{$row->case_type}\",{$row->age}\n";
        }
        Storage::disk('public')->put('patient_ages.csv', $ageCsv);

        // Export application counts CSV
        $applicationCounts = DB::table('patient_records as pr')
            ->join('patient_status_logs as psl', 'psl.patient_id', '=', 'pr.id')
            ->select('pr.case_category', 'pr.case_type', DB::raw('COUNT(*) as application_count'))
            ->whereNull('pr.deleted_at')
            ->whereNull('psl.deleted_at')
            ->where('psl.status', 'Disbursed')
            ->groupBy('pr.case_category', 'pr.case_type')
            ->get();

        $applicationCsv = "case_category,case_type,application_count\n";
        foreach ($applicationCounts as $row) {
            $applicationCsv .= "\"{$row->case_category}\",\"{$row->case_type}\",{$row->application_count}\n";
        }
        Storage::disk('public')->put('application_counts.csv', $applicationCsv);
    }



    // Run Python script to analyze age data CSV and output JSON
    protected function runPythonAgeStats()
    {
        $pythonPath = base_path('venv/Scripts/python.exe');  // Adjust path to your python executable
        $scriptPath = base_path('python/age_statistics.py'); // Your Python script path

        exec("\"$pythonPath\" \"$scriptPath\"", $output, $return_var);

        if ($return_var !== 0) {
            \Log::error("Python age statistics script failed", ['output' => $output]);
        }
    }

    // Return the JSON generated by the Python script
    protected function getPythonJsonOutput()
    {
        $jsonPath = storage_path('app/public/age_stats_output.json');

        if (!file_exists($jsonPath)) {
            return response()->json(['error' => 'No statistics data found'], 404);
        }

        $json = file_get_contents($jsonPath);
        $data = json_decode($json, true);

        return response()->json($data);
    }
}
